// Public surface of the DOM-free core.
export { CARD_H, CARD_R, CARD_W, fmt, mmToPx, type Rect } from './units.ts'
export * from './spec/types.ts'
export { checkCard } from './spec/check.ts'
export { artFileOf, withArtFile, yamlFileName } from './spec/artFile.ts'
export { ART_FIELDS, TOP_LEVEL_FIELDS } from './spec/validate.ts'
export { gluedWords } from './spec/richtext.ts'
export { ICON_NAMES, KNOWN_TAGS } from './icons.ts'
export { FontService, FONT_FILES, FONT_FAMILIES } from './fonts/fontService.ts'
export type { FontId } from './layout/measure.ts'
export { layoutCard, type LayoutContext } from './layout/layout.ts'
export { COMMON } from './layout/frames.ts'
export { lumaMap, meanBrightness, type LumaMap } from './layout/art.ts'
export type { AssetRef, CardLayout } from './layout/model.ts'
export { REQ_BOX } from './frame/reqbox.ts'
export { roundedRectPath } from './frame/paths.ts'
export { renderSvgMarkup, renderSvgString } from './render/svgString.ts'
